---
- hosts: petclinic
  become: yes
  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install dependencies for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add azureuser to Docker group
      ansible.builtin.user:
        name: "azureuser"
        groups: docker
        append: yes

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Create a directory for the application
      file:
        path: /app
        state: directory
    - name: Create a directory for the nginx conf file
      file:
        path: /app/nginx
        state: directory    

    - name: Copy default.conf to the server
      copy:
        src: ../nginx/default.conf 
        dest: /app/nginx/default.conf

    - name: Copy docker-compose.yaml to the server
      copy:
        src: ../docker-compose.yaml 
        dest: /app/docker-compose.yaml

    - name: stop the application using Docker Compose
      command: docker-compose down --remove-orphans
      args:
        chdir: /app

    - name: Remove old Docker image
      shell: docker rmi 3laaharrrr/petclinic:latest || true

    - name: Pull the latest PetClinic image
      command: docker-compose pull
      args:
        chdir: /app        

    - name: Start the application using Docker Compose
      command: docker-compose up -d
      args:
        chdir: /app

    - name: Check if the application is running
      wait_for:
        port: 80
        delay: 30
        timeout: 90

    # Prometheus and Node Exporter Setup
    - name: Create directory for Prometheus setup
      file:
        path: /opt/prometheus
        state: directory

    - name: Copy Prometheus configuration file from local workspace
      copy:
        src: ../prometheus/prometheus.yaml  # Relative path in Jenkins workspace
        dest: /opt/prometheus/prometheus.yaml

    - name: Copy Docker Compose file for Prometheus from local workspace
      copy:
        src: ../prometheus/docker-compose.yaml  # Relative path in Jenkins workspace
        dest: /opt/prometheus/docker-compose.yaml

    - name: stop prometheus using Docker Compose
      command: docker-compose down --remove-orphans
      args:
        chdir: /opt/prometheus       

    - name: Start Prometheus and Node Exporter using Docker Compose
      command: docker-compose up -d
      args:
        chdir: /opt/prometheus

    - name: Check if Prometheus is running
      wait_for:
        port: 9090
        delay: 10
        timeout: 60

    - name: Check if Node Exporter is running
      wait_for:
        port: 9100
        delay: 10
        timeout: 60        
